name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - edit/**
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build static site
        run: bun run build:static
        env:
          # Use "/" for https://<username>.github.io/
          # Use "/<repo-name>/" for https://<username>.github.io/<repo-name>/
          GH_PAGES_BASE: "/somilsin_portfolio/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/client

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
